jobs: 100
cluster: "sbatch --parsable --partition={cluster.partition} --time={cluster.time} --mem={resources.mem_gb}G --cpus-per-task={threads} --job-name={rule} --output=logs/slurm/{rule}-%j.out"
default-resources:
  - mem_gb=8
  - threads=1
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True

cluster-config: "profile/slurm/cluster.yaml"

