# metadata
metadata: metadata.tsv
manifest: manifest.csv

# parameters
#
params:
  remove:   # remove adapter or primer
    forward_sequence_515F: CCTAYGGGRBGCASCAG
    reverse_sequence_806R: GGACTACNNGGGTATCTAAT
    remove_primer_threads:   8
  denoise:      # denosie by dada2 or deblur
    dada2pe_trunc_len_f: 240
    dada2pe_trunc_len_r: 190
    dada2pe_trim_left_f: 0
    dada2pe_trim_left_r: 0
    dada2pe_max_ee_f: 2
    dada2pe_max_ee_r: 2
    dada2pe_trunc_q: 2
    dada2pe_pooling_method: independent
    dada2pe_chimera_method: consensus
    dada2pe_min_fold_parent_over_abundance: 1
    dada2pe_n_reads_learn: 1000000
    dada2pe_hashed_feature_ids: --p-hashed-feature-ids
    dada2pe_threads: 8
  classifier: # taxonomic classification 
    refseqs:  /data/share/database/qiime2_db/silva/silva-full-length.fasta
    reftax:   /data/share/database/qiime2_db/silva/silva-full-taxonomy.tsv
    classify_method: naive-bayes        # taxonomic classification method (choose from: consensus-blast, naive-bayes)
    classify_method: weighted_classifier.qza
    classify_method: weighted_class.qza
    feature_classifier_threads: 8
  filter_repseq:
    exclude_terms: mitochondria,chloroplast,eukaryota    # filter table and representative sequences by taxonomy
    repseqs_to_filter: repseqs_to_filter.tsv
  diversity: # representative sequence outlier detection using odseq
    odseq_distance_metric: linear # choose from: linear, affine
    odseq_bootstrap_replicates: 10
    odseq_threshold: 0.025      # probability to be at right of the bootstrap scores distribution
    core_sampling_depth: 500  # subsampling
    alpha_max_depth: 500      # subsampling
    beta_group_column: region   # beta group significance (choose a column from metadata to test)
    alignment_mafft_threads:   8
    phylogeny_fasttree_threads: 8
    diversity_core_metrics_phylogenetic_threads: 8
  report: # report theme (choose from: github, gothic, newsprint, night, pixyll, whitey)
    report_theme: github

# result
result:
  import:    result/01-import/
  remove:    result/02-remove/ 
  denoise:   result/03-denoise/   
  taxonomy:  result/04-taxonomy/
  tree:      result/05-alignment-tree/
  alpha:     result/06-alpha-diversity/
  beta:      result/07-beta-diversity/
  report:    result/08-report/

# log 
logs:
  import:    result/logs/01-import/
  remove:    result/logs/02-remove/ 
  denoise:   result/logs/03-denoise/   
  taxonomy:  result/logs/04-taxonomy/
  tree:      result/logs/05-alignment-tree/
  alpha:     result/logs/06-alpha-diversity/
  beta:      result/logs/07-beta-diversity/
  report:    result/logs/08-report/
